version: '2'
services:
  php:
    image: bscheshir/php:7.0.13-fpm-4yii2-xdebug
    restart: always
    volumes:
      - ../php-code:/var/www/html #php-code
    depends_on:
      - db
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.88.241 remote_port=9007 var_display_max_data=1024 var_display_max_depth=5"
      PHP_IDE_CONFIG: "serverName=petshelter"
  nginx:
    image: nginx:1.11.5-alpine
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ../nginx-conf:/etc/nginx/conf.d #nginx-conf
      - ../nginx-logs:/var/log/nginx #nginx-logs
  db:
    image: mysql:5.7.15
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ../mysql-data/db:/var/lib/mysql #mysql-data
    environment:
      MYSQL_ROOT_PASSWORD: petshelter
      MYSQL_DATABASE: petshelter
      MYSQL_USER: petshelter
      MYSQL_PASSWORD: petshelter

